### PR TITLE
[IOS] FIX: Return original filename instead of FullSizeRender

### LINKED ISSUE #976: [Bug report][iOS] For assets with adjustments/filters, return original name instead of FullSizeRender.*
### Version

2.7.1

### Platforms

iOS, macOS

### Device Model

Any

### flutter info

```sh
flutter 3.10.6
```

### How to reproduce?

* Using native photos app, turn off the video of a live photo.
* Get the title for that asset. It shows FullSizeRender.jpg as asset name.

Related Threads:

https://discussions.apple.com/thread/6849595

Sample reference:
How owncloud iOS app had fixed similar issue in the past:
https://github.com/owncloud/ios-app/pull/522/files#diff-8f5e53a932df183d0057b50091c72ea54c1524c4917b548a973448a95234e5ee
image

### Logs

```sh
NA
```

### Example code (optional)

_No response_

### Contact

ua741

### PR DESCRIPTION
**Pull request by xick**
- Add method **_getUntouchedResource_** to retrieve original photo/video instead of altered one (with adjustments / filters)
- **Fix**: When retrieving an asset title ( with _entity.title_ or _entity.titleAsync_) now returns original file name instead of '**_FullSizeRender.*_**' if this has adjustments.

Related Issues:
Fixes #976
Fixes https://github.com/immich-app/immich/issues/4088

### CODE REVIEW

File: ios/Classes/core/PHAsset+PM_COMMON.h [hunk 1]
```diff
@@ -29,6 +29,7 @@ NS_ASSUME_NONNULL_BEGIN
 - (nullable NSString*)mimeType;
 - (BOOL)isAdjust;
 - (PHAssetResource *)getAdjustResource;
+- (PHAssetResource *)getUntouchedResource;
```
Comment (AlexV525) [inline ios/Classes/core/PHAsset+PM_COMMON.h:32]: This seems to affect the file of Live Photos. What's the difference between them? Any specs?

Comment (xick) [reply ios/Classes/core/PHAsset+PM_COMMON.h:32]: _getAdjustResource_ return by default media with adjustments ( PHAssetResourceTypeFullSizePhoto/Video) if there are any.
_getUntouchedResource_ will always return original asset (PHAssetResourceTypePhoto/*Video).
LivePhotos are not affected by this, because there are already dedicated methods to deal with them. For example, when retrieving filename of an asset, will check if media type is LivePhoto and use the dedicated method:

```
- (NSString *)originalFilenameWithSubtype:(int)subtype {
    if (@available(iOS 9.1, *)) {
        if ([self isLivePhoto] && subtype == PHAssetMediaSubtypePhotoLive) {
            return [self getLivePhotosResource].originalFilename;
        }
    }
    PHAssetResource *resource = [self getUntouchedResource];
    if (resource) {
        return resource.originalFilename;
    }
```

_getLivePhotosResource_ currently will always returns original video asset ( PHAssetResourceTypePairedVideo), and there are no method to retrieve the asset with adjustments, hence we could add this possibility.

Comment (xick) [reply ios/Classes/core/PHAsset+PM_COMMON.h:32]: Another thing I noticed, this code path is useless in 'getAdjustResource': 

```
- (PHAssetResource *)getAdjustResource {
    NSArray<PHAssetResource *> *resources = [PHAssetResource assetResourcesForAsset:self];
    if (resources.count == 0) {
        return nil;
    }
    
    if (resources.count == 1) {
        return resources[0];
    }
    
// // // useless, !isAdjust means resource count is one, 
// // // so will always be skipped by the previous check ( if resources.count == 1)

    if (![self isAdjust]) {
        for (PHAssetResource *res in resources) {
            if (self.mediaType == PHAssetMediaTypeImage
                && res.type == PHAssetResourceTypePhoto) {
                return res;
            }
            
            if (self.mediaType == PHAssetMediaTypeVideo
                && res.type == PHAssetResourceTypeVideo) {
                return res;
            }
        }
        
        return nil;
    }
    // // // 

...
```

**Comment by AlexV525** [comment]
@xick Could you add the CHANGELOG entry and update the branch?

**Comment by xick** [comment]
Done.  I don't know if I should have pushed a single commit instead, sorry but I'm not familiar with PR.

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,13 @@ that can be found in the LICENSE file. -->
 
 # CHANGELOG
 
+## 2.7.3
```
Comment (AlexV525) [inline CHANGELOG.md:7]: We didn't publish 2.7.2 yet, so these should be under the 2.7.2 section.

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,13 @@ that can be found in the LICENSE file. -->
...
+
+### Fixes
+
+- [iOS] Add PHAsset extension method `getUntouchedResource` to retrieve original media instead of one with adjustments / filters.
+- [iOS] Fix: When retrieving an asset title, now returns original file name instead of `FullSizeRender.*` if this has adjustments. (#976)
```
Comment (AlexV525) [inline CHANGELOG.md:12]:
```suggestion
- Retrieve original media instead of one with adjustments/filters for subtype files on iOS. (#976)
- Returns original file name instead of `FullSizeRender.*` if this has adjustments on iOS. (#976)
```

**Comment by AlexV525** [comment]
> Done. I don't know if I should have pushed a single commit instead, sorry but I'm not familiar with PR.

You don't have to, we will make a squash merge.

**Review by AlexV525 — APPROVED** [review]

**Comment by alextran1502** [comment]
Hello @AlexV525, I apologize for the ping and the forbidden question. 

Do you know when we can expect a new release with the library? 

Thank you for your work!
Alex

**Comment by AlexV525** [comment]
> Do you know when we can expect a new release with the library?

Now. :)

**Comment by alextran1502** [comment]
@AlexV525 Thanks Alex! I appreciate you so much

**Comment by patelnirav48** [comment]
@AlexV525 Using latest version of library still getting FullSizeRender.jpg instead HEIC image and original file name. This happens when i use portrait image in iOS.

**Comment by AlexV525** [comment]
@xick Is your fix managed to cover the above case?

**Comment by alextran1502** [comment]
@patelnirav48 @AlexV525 it works fine on my end for getting the correct file name for Portrait mode on Iphone 12 Pro

**Comment by AlexV525** [comment]
@patelnirav48 Please share details so everyone at here can probably help to sort out the case.

**Comment by patelnirav48** [comment]
Screenshot at Mar 05 17-02-15

1) I captured from camera as Portrait as above

**Comment by patelnirav48** [comment]
@alextran1502 @AlexV525 I'm using latest version of wechat_assets_picker, and that also using latest version of photo manager 3.0.0.. When i pick from gallery its return FullSizeRender.jpg.. even extension get changed with file name.

**Comment by maslanypotwor** [comment]
I was watching this PR and got notification so I checked from my side and indeed in Immich I can see that portrait photo I just took and backed up is indeed IMG_0327.HEIC

**Comment by AlexV525** [comment]
> @alextran1502 @AlexV525 I'm using latest version of wechat_assets_picker, and that also using latest version of photo manager 3.0.0.. When i pick from gallery its return FullSizeRender.jpg.. even extension get changed with file name.

So you're accessing with `.file`?

**Comment by patelnirav48** [comment]
> > @alextran1502 @AlexV525 I'm using latest version of wechat_assets_picker, and that also using latest version of photo manager 3.0.0.. When i pick from gallery its return FullSizeRender.jpg.. even extension get changed with file name.
> 
> So you're accessing with `.file`?

Accessing as .originFile

**Comment by AlexV525** [comment]
I can reproduce this using iPhone 12 with iOS 17.3.1.

**Comment by alextran1502** [comment]
@AlexV525 Immich was still using 3.0.0-dev5, I wonder if you can test with that version to see if you can still reproduce this?

**Comment by AlexV525** [comment]
> @AlexV525 Immich was still using 3.0.0-dev5, I wonder if you can test with that version to see if you can still reproduce this?

I'm using 3.0.0.

**Comment by patelnirav48** [comment]
@alextran1502 I tested with 3.0.0-dev5 its working fine by keeping file name and extension as it is. Just it's removing portrait background blur effect from the image. 

CC. @AlexV525

**Comment by AlexV525** [comment]
> @alextran1502 I tested with 3.0.0-dev5 its working fine (It's keeping file name and extension as it is). Just it's removing portrait background blur effect from the image.

So are you running the same issue using the 3.0.0? It includes changes from dev.5 for sure.

**Comment by patelnirav48** [comment]
> > @alextran1502 I tested with 3.0.0-dev5 its working fine (It's keeping file name and extension as it is). Just it's removing portrait background blur effect from the image.
> 
> So are you running the same issue using the 3.0.0? It includes changes from dev.5 for sure.

In 3.0.0, It's not working.. but 3.0.0-dev5 its working, but just it's removing portrait background blur effect from the image.

**Comment by patelnirav48** [comment]
> You can use `git bisect` to find out which commit introduces the regression. AFAIK there are no related changes.

Ah sorry, you made changes already before few hours, so its working. https://prnt.sc/Gp3PCJlpkfvJ. Thanks

**Comment by benmccann** [comment]
If I understand correctly, it seems that there were remaining issues (https://github.com/fluttercandies/flutter_photo_manager/issues/976) fixed in https://github.com/fluttercandies/flutter_photo_manager/pull/1098, but not yet released. So 3.0.0-dev.5 works, 3.0.0 does not, and when 3.0.1 is released then it should work again.
